# Generated by Django 2.1 on 2018-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='order_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
