# Generated by Django 2.1 on 2018-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180822_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderlog',
            unique_together=set(),
        ),
    ]
