# Generated by Django 2.1 on 2018-08-14 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('customers', '0002_auto_20180814_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learninglog',
            unique_together={('customer', 'course')},
        ),
    ]
