# Generated by Django 2.1 on 2018-08-14 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20180814_1620'),
        ('customers', '0003_auto_20180814_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='orderlog',
            unique_together={('customer', 'course')},
        ),
    ]
