# Generated by Django 2.1 on 2018-08-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='codename',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
