# Generated by Django 2.1 on 2018-08-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='customer',
            new_name='user',
        ),
    ]
