# Generated by Django 2.1 on 2018-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180814_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/common/heroes/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
