# Generated by Django 2.1 on 2018-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180824_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reward_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
