# Generated by Django 2.1 on 2018-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminlog_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='new_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='old_data',
            field=models.TextField(blank=True),
        ),
    ]
